version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - if test -d "LambdaDev" && git diff HEAD $(git rev-parse HEAD)^ --name-only | grep "^LambdaDev/" >/dev/null; then cd LambdaDev && npm install && zip -r LambdaDev.zip * && aws s3 cp LambdaDev.zip s3://multi-lambda/LambdaDev.zip && aws lambda update-function-code --function-name LambdaDev --s3-bucket multi-lambda --s3-key LambdaDev.zip && cd ..; fi
      - if test -d "lambdaSF" && git diff HEAD $(git rev-parse HEAD)^ --name-only | grep "^lambdaSF/" >/dev/null; then cd lambdaSF && npm install && zip -r lambdaSF.zip * && aws s3 cp lambdaSF.zip s3://multi-lambda/lambdaSF.zip && aws lambda update-function-code --function-name lambdaSF --s3-bucket multi-lambda --s3-key lambdaSF.zip && cd ..; fi
