version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - git clone https://github.com/sahitya15/Lambda-POC.git
      - cd Lambda-POC
      - ls -al
      - |
        LAMBDA_FUNCTION_NAME=${LAMBDA_FUNCTION_NAME_1};
        LAMBDA_DIRECTORY=${LAMBDA_DIRECTORY_NAME1};
        S3_BUCKET_NAME=${BUCKET_NAME};
        if git diff --name-only HEAD^ HEAD | grep -q "^$LAMBDA_DIRECTORY/"; then
          echo "Detected changes in $LAMBDA_DIRECTORY directory, updating $LAMBDA_FUNCTION_NAME function..."
          cd $LAMBDA_DIRECTORY
          npm install
          zip -r $LAMBDA_FUNCTION_NAME.zip *
          aws s3 cp $LAMBDA_FUNCTION_NAME.zip s3://$S3_BUCKET_NAME/$LAMBDA_FUNCTION_NAME.zip
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET_NAME --s3-key $LAMBDA_FUNCTION_NAME.zip
          cd ..
        fi
      - |
        LAMBDA_FUNCTION_NAME=${LAMBDA_FUNCTION_NAME_2};
        LAMBDA_DIRECTORY=${LAMBDA_DIRECTORY_NAME2};
        S3_BUCKET_NAME=${BUCKET_NAME};
        if git diff --name-only HEAD^ HEAD | grep -q "^$LAMBDA_DIRECTORY/"; then
          echo "Detected changes in $LAMBDA_DIRECTORY directory, updating $LAMBDA_FUNCTION_NAME function..."
          cd $LAMBDA_DIRECTORY
          npm install
          zip -r $LAMBDA_FUNCTION_NAME.zip *
          aws s3 cp $LAMBDA_FUNCTION_NAME.zip s3://$S3_BUCKET_NAME/$LAMBDA_FUNCTION_NAME.zip
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET_NAME --s3-key $LAMBDA_FUNCTION_NAME.zip
          cd ..
        fi
