version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - if [ "$CODEBUILD_WEBHOOK_TRIGGER" != "branch/main" ]; then
          echo "Skipping deployment for branch $CODEBUILD_WEBHOOK_TRIGGER";
          exit 0;
        fi
      - for func in LambdaDev lambdaSF; do
          if [[ $CODEBUILD_SOURCE_VERSION == *"$func"* ]]; then
            cd $func;
            npm install;
            zip -r $func.zip *;
            aws s3 cp $func.zip s3://$S3_BUCKET/$func.zip;
            aws lambda update-function-code --function-name $func --s3-bucket $S3_BUCKET --s3-key $func.zip;
          fi
        done

