version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - git fetch --all
      - >
        git diff --name-only $CODEBUILD_SOURCE_VERSION $(git merge-base $CODEBUILD_SOURCE_VERSION origin/main) |
        grep -E '^lambdaDev/|^lambdaSF/' |
        cut -d'/' -f1 |
        uniq |
        while read -r function_name; do
          echo "Updating $function_name function"
          cd "$function_name"
          npm install
          zip -r "$function_name".zip *
          aws s3 cp "$function_name".zip s3://multi-lambda/"$function_name".zip
          aws lambda update-function-code --function-name "$function_name" --s3-bucket multi-lambda --s3-key "$function_name".zip
          cd ..
        done
