version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd LambdaDev
      - npm install
      - zip -r LambdaDev.zip *
      - aws s3 cp LambdaDev.zip s3://multi-lambda/LambdaDev.zip
      - if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/main" ]; then
          aws lambda update-function-code --function-name LambdaDev --s3-bucket multi-lambda --s3-key LambdaDev.zip;
        fi
      - cd ../lambdaSF
      - npm install
      - zip -r lambdaSF.zip *
      - aws s3 cp lambdaSF.zip s3://multi-lambda/lambdaSF.zip
      - if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/main" ]; then
          aws lambda update-function-code --function-name lambdaSF --s3-bucket multi-lambda --s3-key lambdaSF.zip;
        fi
