version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd lambda1 && npm install
      - cd lambda2 && npm install
      - cd lambda3 && npm install
      - cd lambda4 && npm install
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket my-bucket --output-template-file output.yaml
artifacts:
  files:
    - output.yaml
