version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - git clone https://github.com/sahitya15/Lambda-POC.git
      - cd Lambda-POC
      - ls -al
      - |
        # Check if there are changes in the LambdaDev directory
        if git diff --name-only HEAD^ HEAD | grep -q "^LambdaDev/"; then
          echo "Detected changes in LambdaDev directory, updating LambdaDev function..."
          # Navigate to the LambdaDev directory
          cd LambdaDev
          # Install dependencies and package code
          npm install
          zip -r LambdaDev.zip *
          # Upload code package to S3
          aws s3 cp LambdaDev.zip s3://multi-lambda/LambdaDev.zip
          # Update Lambda function with new code package
          aws lambda update-function-code --function-name LambdaDev --s3-bucket multi-lambda --s3-key LambdaDev.zip
          # Navigate back to the root directory
          cd ..
        fi
        # Check if there are changes in the lambdaSF directory
        if git diff --name-only HEAD^ HEAD | grep -q "^lambdaSF/"; then
          echo "Detected changes in lambdaSF directory, updating lambdaSF function..."
          # Navigate to the lambdaSF directory
          cd lambdaSF
          # Install dependencies and package code
          npm install
          zip -r lambdaSF.zip *
          # Upload code package to S3
          aws s3 cp lambdaSF.zip s3://multi-lambda/lambdaSF.zip
          # Update Lambda function with new code package
          aws lambda update-function-code --function-name lambdaSF --s3-bucket multi-lambda --s3-key lambdaSF.zip
          # Navigate back to the root directory
          cd ..
        fi
