version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd LambdaDev
      - npm install
      - zip -r LambdaDev.zip *
      - aws lambda update-function-code --function-name LambdaDev --zip-file fileb://LambdaDev.zip
      - cd ../lambdaSF
      - npm install
      - zip -r lambdaSF.zip *
      - aws lambda update-function-code --function-name lambdaSF --zip-file fileb://lambdaSF.zip
