---
version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E
        "(LambdaDev|lambdaSF)\.js")
      - >-
        if [ -n "$CHANGED_FILES" ]; then
          echo "Changes detected in: $CHANGED_FILES"
          npm run build
          for LAMBDA in LambdaDev lambdaSF; do
            if [ -n "$(echo $CHANGED_FILES | grep ${LAMBDA}.js)" ]; then
              if aws s3 ls s3://multi-lambda/${LAMBDA}.zip; then
                aws s3 cp ${LAMBDA}.zip s3://multi-lambda/${LAMBDA}.zip
                echo "Deployment package for ${LAMBDA} updated in S3."
              else
                echo "No deployment package found for ${LAMBDA} in S3. Skipping update."
              fi
            fi
          done
        else
          echo "No changes detected. Skipping build and push."
        fi

  post_build:
  commands:
    - |
      for LAMBDA in LambdaDev lambdaSF; do
        if aws s3 ls s3://multi-lambda/${LAMBDA}.zip; then
          aws lambda update-function-code --function-name ${LAMBDA} --s3-bucket multi-lambda --s3-key ${LAMBDA}.zip
          echo "${LAMBDA} updated with latest deployment package."
        else
          echo "No deployment package found for ${LAMBDA}. Skipping update."
        fi
      done
