version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - zip -r LambdaDev.zip *
      - zip -r lambdaSF.zip *
  post_build:
    commands:
      - aws s3 cp LambdaDev.zip s3://my-bucket/function1.zip
      - aws s3 cp lambdaSF.zip s3://my-bucket/function2.zip
artifacts:
  files:
    - LambdaDev.zip
    - lambdaSF.zip
