version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - git fetch origin main
      - git diff --name-only $CODEBUILD_SOURCE_VERSION $(git merge-base $CODEBUILD_SOURCE_VERSION origin/main) | while read -r line; do
          if [[ "$line" == "lambdaDev/"* ]]; then
            echo "Updating LambdaDev function"
            cd LambdaDev
            npm install
            zip -r LambdaDev.zip *
            aws s3 cp LambdaDev.zip s3://multi-lambda/LambdaDev.zip
            aws lambda update-function-code --function-name LambdaDev --s3-bucket multi-lambda --s3-key LambdaDev.zip
            cd ..
          elif [[ "$line" == "lambdaSF/"* ]]; then
            echo "Updating lambdaSF function"
            cd lambdaSF
            npm install
            zip -r lambdaSF.zip *
            aws s3 cp lambdaSF.zip s3://multi-lambda/lambdaSF.zip
            aws lambda update-function-code --function-name lambdaSF --s3-bucket multi-lambda --s3-key lambdaSF.zip
            cd ..
          fi
        done
