version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - git clone https://github.com/sahitya15/Lambda-POC.git
      - cd Lambda-POC.git
      - ls -al
      - |
        # Define variables
        lambda_names=("LAMBDA_NAME_1" "LAMBDA_NAME_2")
        s3_bucket="S3_BUCKET_NAME"

        # Loop through each Lambda function and directory
        for lambda_name in "${lambda_names[@]}"; do
          # Check if there are changes in the directory
          if git diff --name-only HEAD^ HEAD | grep -q "^${lambda_name}/"; then
            echo "Detected changes in ${lambda_name} directory, updating ${lambda_name} function..."
            # Navigate to the directory
            cd ${lambda_name}
            # Install dependencies and package code
            npm install
            zip -r ${lambda_name}.zip *
            # Upload code package to S3
            aws s3 cp ${lambda_name}.zip s3://${s3_bucket}/${lambda_name}.zip
            # Update Lambda function with new code package
            aws lambda update-function-code --function-name ${lambda_name} --s3-bucket ${s3_bucket} --s3-key ${lambda_name}.zip
            # Navigate back to the root directory
            cd ..
          fi
        done
