version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "functions=$functions"
      - echo "directories=$directories"
      - set -x
      - declare -a functions=("LambdaDev" "lambdaSF")
        declare -a directories=("LambdaDev" "lambdaSF")
      - set +x
      - |
        for ((i=0; i<${#functions[@]}; i++)); do
          function_name="${functions[$i]}"
          directory_name="${directories[$i]}"
          echo "Updating $function_name with code from $directory_name"
          cd "$directory_name"
          npm install
          zip -r "$function_name.zip" .
          aws s3 cp "$function_name.zip" "s3://dev-cicd-sis/$function_name.zip"
          aws lambda update-function-code --function-name "$function_name" --s3-bucket multi-lambda --s3-key "$function_name.zip"
          cd ..
        done
