version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - git diff HEAD^ HEAD --name-only | while read -r line ; do
      -   folder=$(echo $line | cut -d'/' -f1)
      -   if [ "$folder" = "LambdaDev" ]; then
      -     echo "Detected a change in LambdaDev folder, updating the corresponding lambda function..."
      -     cd $folder
      -     npm install
      -     zip -r ../$folder.zip *
      -     aws s3 cp ../$folder.zip s3://multi-lambda/$folder.zip
      -     aws lambda update-function-code --function-name LambdaDev --s3-bucket multi-lambda --s3-key LambdaDev.zip
      -     break
      -   elif [ "$folder" = "lambdaSF" ]; then
      -     echo "Detected a change in lambdaSF folder, updating the corresponding lambda function..."
      -     cd $folder
      -     npm install
      -     zip -r ../$folder.zip *
      -     aws s3 cp ../$folder.zip s3://multi-lambda/$folder.zip
      -     aws lambda update-function-code --function-name lambdaSF --s3-bucket multi-lambda --s3-key lambdaSF.zip
      -     break
      -   fi
      - done
