version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd LambdaDev && npm install
      - cd ../lambdaSF && npm install
      - cd ..
      
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket multi-lambda --s3-prefix cicd/lambda-functions --output-template-file output.yaml

artifacts:
  files:
    - output.yaml
